name: CI/CD Deploy

on:
  push:
    branches:
      - main # jab main branch me push hoga tab chalega

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker Hub login
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      # Docker image build & push
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USER }}/express-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # Deploy on EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USER }}/express-app:latest
            docker stop express-app || true
            docker rm express-app || true
            docker run -d -p 3000:3000 --name express-app ${{ secrets.DOCKER_USER }}/express-app:latest
