name: CI/CD Deploy (Docker Only)

on:
  push:
    branches:
      - main # triggers workflow when pushing to main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Fix Git safe directory issue
      - name: Set Git safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      # 3️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      # 4️⃣ Build Docker image and push
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USER }}/express-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
