name: CI/CD Deploy (Docker + Server)

on:
  push:
    branches:
      - main # triggers workflow when pushing to main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Fix Git safe directory issue
      - name: Set Git safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      # 3️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      # 4️⃣ Build Docker image and push
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USER }}/express-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # 5️⃣ Deploy on remote server via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USER }}/express-app:latest
            docker stop express-app || true
            docker rm express-app || true
            docker run -d -p 3000:3000 --name express-app ${{ secrets.DOCKER_USER }}/express-app:latest
