name: Deploy Express App

on:
  push:
    branches:
      - main # deploy on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test --if-present

      - name: Build app
        run: npm run build --if-present

      # --- Deploy Section ---
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }} # EC2 public DNS
          username: ${{ secrets.SERVER_USER }} # EC2 user (ubuntu)
          key: ${{ secrets.SERVER_SSH_KEY }} # your PEM key
          port: 22
          script: |
            mkdir -p /var/www/express-app
            cd /var/www/express-app
            git pull origin main
            npm install --production
            pm2 restart express-app || pm2 start index.js --name express-app
            pm2 save
