name: CI/CD Deploy (Local VM with K8s)

on:
  push:
    branches:
      - main # triggers workflow when pushing to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Fix Git safe directory issue
      - name: Set Git safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      # 3️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      # 4️⃣ Build Docker image and push
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USER }}/express-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # 5️⃣ Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      # 6️⃣ Configure kubeconfig from GitHub Secret
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config

      # 7️⃣ Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/express-deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout status deployment/express-app
