name: CI/CD Deploy

on:
  push:
    branches:
      - main # triggers workflow when pushing to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false # disable submodules if not used

      # 2️⃣ Fix Git safe directory issue
      - name: Set Git safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      # 3️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      # 4️⃣ Build Docker image and push
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USER }}/express-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # 5️⃣ Deploy on EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Add user to Docker group (for permissions)
            sudo usermod -aG docker $USER || true
            newgrp docker || true

            # Pull the latest Docker image
            sudo docker pull ${{ secrets.DOCKER_USER }}/express-app:latest

            # Stop and remove the old container
            sudo docker stop express-app || true
            sudo docker rm express-app || true

            # Remove dangling images
            sudo docker rmi -f $(sudo docker images -f "dangling=true" -q) || true

            # Run new container
            sudo docker run -d -p 3000:3000 --name express-app ${{ secrets.DOCKER_USER }}/express-app:latest

            # Optional fallback with PM2 if Docker fails
            if ! docker ps | grep -q express-app; then
              echo "Docker failed, using PM2 fallback"
              pm2 stop express-app || true
              pm2 delete express-app || true
              pm2 start index.js --name express-app
              pm2 save
            fi
