name: CI/CD Deploy (Docker + Self-Hosted Runner)

on:
  push:
    branches:
      - main # trigger only when pushing to main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted # runs directly inside your VMware VM

    steps:
      # Step 1: Checkout repo code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build Docker image (no cache)
      - name: Build Docker image
        run: |
          docker build --no-cache -t express-app:latest .

      # Step 3: Stop and remove old container (if exists)
      - name: Stop old container
        run: |
          docker stop express-app || true
          docker rm express-app || true

      # Step 4: Run new container
      - name: Run new container
        run: |
          docker run -d --name express-app -p 3000:3000 express-app:latest
